// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRuntimesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRuntimesResponse {
    #[prost(message, repeated, tag = "1")]
    pub runtimes: ::prost::alloc::vec::Vec<Runtime>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Runtime {
    #[prost(string, tag = "1")]
    pub language: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub image: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub requires_vendor: bool,
    #[prost(string, repeated, tag = "5")]
    pub aliases: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "6")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub default_entrypoint: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub compile_phase: ::core::option::Option<RuntimePhase>,
    #[prost(message, optional, tag = "9")]
    pub run_phase: ::core::option::Option<RuntimePhase>,
    #[prost(message, optional, tag = "10")]
    pub default_limits: ::core::option::Option<RuntimeLimits>,
    #[prost(message, optional, tag = "11")]
    pub max_limits: ::core::option::Option<RuntimeLimits>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RuntimePhase {
    #[prost(string, repeated, tag = "1")]
    pub command: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "2")]
    pub enabled: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RuntimeLimits {
    #[prost(uint32, tag = "1")]
    pub compile_timeout_ms: u32,
    #[prost(uint32, tag = "2")]
    pub run_timeout_ms: u32,
    #[prost(uint64, tag = "3")]
    pub memory_limit_bytes: u64,
    #[prost(uint32, tag = "4")]
    pub cpu_millis: u32,
    #[prost(uint64, tag = "5")]
    pub output_bytes: u64,
    #[prost(uint64, tag = "6")]
    pub archive_bytes: u64,
    #[prost(uint64, tag = "7")]
    pub stdin_bytes: u64,
    #[prost(uint32, tag = "8")]
    pub args: u32,
    #[prost(uint64, tag = "9")]
    pub arg_bytes: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitGoProjectRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub archive_targz: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub entrypoint: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub stdin: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag = "4")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag = "5")]
    pub compile_timeout_ms: u32,
    #[prost(uint32, tag = "6")]
    pub run_timeout_ms: u32,
    #[prost(uint64, tag = "7")]
    pub memory_limit_bytes: u64,
    #[prost(uint32, tag = "8")]
    pub cpu_millis: u32,
    #[prost(uint64, tag = "9")]
    pub max_output_bytes: u64,
    #[prost(string, tag = "10")]
    pub language: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitGoProjectResponse {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "JobStatus", tag = "2")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetJobRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamJobEventsRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub after_sequence: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelJobRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelJobResponse {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "JobStatus", tag = "2")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Job {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "JobStatus", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub language: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub runtime: ::core::option::Option<Runtime>,
    #[prost(string, tag = "5")]
    pub entrypoint: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag = "7")]
    pub compile_timeout_ms: u32,
    #[prost(uint32, tag = "8")]
    pub run_timeout_ms: u32,
    #[prost(uint64, tag = "9")]
    pub memory_limit_bytes: u64,
    #[prost(uint32, tag = "10")]
    pub cpu_millis: u32,
    #[prost(uint64, tag = "11")]
    pub max_output_bytes: u64,
    #[prost(message, optional, tag = "12")]
    pub result: ::core::option::Option<JobResult>,
    #[prost(string, tag = "13")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub started_at: ::prost::alloc::string::String,
    #[prost(string, tag = "16")]
    pub finished_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobResult {
    #[prost(bytes = "vec", tag = "1")]
    pub stdout: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub stderr: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub compile_stdout: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub compile_stderr: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "5")]
    pub exit_code: i32,
    #[prost(int32, tag = "6")]
    pub signal: i32,
    #[prost(uint64, tag = "7")]
    pub wall_time_ms: u64,
    #[prost(uint64, tag = "8")]
    pub memory_peak_bytes: u64,
    #[prost(bool, tag = "9")]
    pub stdout_truncated: bool,
    #[prost(bool, tag = "10")]
    pub stderr_truncated: bool,
    #[prost(uint64, tag = "11")]
    pub cpu_usage_usec: u64,
    #[prost(uint64, tag = "12")]
    pub cpu_throttled_usec: u64,
    #[prost(uint64, tag = "13")]
    pub pids_peak: u64,
    #[prost(uint64, tag = "14")]
    pub memory_oom_kill_count: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobEvent {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub sequence: u64,
    #[prost(enumeration = "JobStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JobStatus {
    Unspecified = 0,
    Queued = 1,
    Validating = 2,
    Compiling = 3,
    Running = 4,
    Succeeded = 5,
    CompileFailed = 6,
    RuntimeFailed = 7,
    TimeLimitExceeded = 8,
    MemoryLimitExceeded = 9,
    OutputLimitExceeded = 10,
    Canceled = 11,
    SystemError = 12,
}
impl JobStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "JOB_STATUS_UNSPECIFIED",
            Self::Queued => "JOB_STATUS_QUEUED",
            Self::Validating => "JOB_STATUS_VALIDATING",
            Self::Compiling => "JOB_STATUS_COMPILING",
            Self::Running => "JOB_STATUS_RUNNING",
            Self::Succeeded => "JOB_STATUS_SUCCEEDED",
            Self::CompileFailed => "JOB_STATUS_COMPILE_FAILED",
            Self::RuntimeFailed => "JOB_STATUS_RUNTIME_FAILED",
            Self::TimeLimitExceeded => "JOB_STATUS_TIME_LIMIT_EXCEEDED",
            Self::MemoryLimitExceeded => "JOB_STATUS_MEMORY_LIMIT_EXCEEDED",
            Self::OutputLimitExceeded => "JOB_STATUS_OUTPUT_LIMIT_EXCEEDED",
            Self::Canceled => "JOB_STATUS_CANCELED",
            Self::SystemError => "JOB_STATUS_SYSTEM_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOB_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "JOB_STATUS_QUEUED" => Some(Self::Queued),
            "JOB_STATUS_VALIDATING" => Some(Self::Validating),
            "JOB_STATUS_COMPILING" => Some(Self::Compiling),
            "JOB_STATUS_RUNNING" => Some(Self::Running),
            "JOB_STATUS_SUCCEEDED" => Some(Self::Succeeded),
            "JOB_STATUS_COMPILE_FAILED" => Some(Self::CompileFailed),
            "JOB_STATUS_RUNTIME_FAILED" => Some(Self::RuntimeFailed),
            "JOB_STATUS_TIME_LIMIT_EXCEEDED" => Some(Self::TimeLimitExceeded),
            "JOB_STATUS_MEMORY_LIMIT_EXCEEDED" => Some(Self::MemoryLimitExceeded),
            "JOB_STATUS_OUTPUT_LIMIT_EXCEEDED" => Some(Self::OutputLimitExceeded),
            "JOB_STATUS_CANCELED" => Some(Self::Canceled),
            "JOB_STATUS_SYSTEM_ERROR" => Some(Self::SystemError),
            _ => None,
        }
    }
}
include!("sandkasten.v1.tonic.rs");
// @@protoc_insertion_point(module)
